#!/usr/local/bin/python3

import sys

command_name = __file__.rsplit('/', 1)[1]

if len(sys.argv) < 2:
    print('Usage:', command_name, 'in_file [out_file]')
    exit()

in_file_name = sys.argv[1]
try:
    in_file = open(in_file_name)
except FileNotFoundError:
    print(command_name + ':', in_file_name + ":", 'No such file or directory')
    exit()
except IsADirectoryError:
    print(command_name + ':', in_file_name + ":", 'Is a directory')
    exit()

if len(sys.argv) > 2:
    out_file_name = sys.argv[2]
    try:
        out_file = open(out_file_name, 'w')
    except FileNotFoundError:
        print(command_name + ':', out_file_name + ":", 'No such file or directory')
        exit()
    except IsADirectoryError:
        print(command_name + ':', out_file_name + ":", 'Is a directory')
        exit()
else:
    out_file_name = 'stackoverflowify.out'
    try:
        out_file = open(out_file_name, 'w')
    except:
        print(command_name + ':', 'ERROR [Internal]: Could not open file \'' + out_file_name + '\'.')
        exit()

in_file_lines = in_file.readlines()
in_file.close()

out_file.write(''.join(['    ' + line for line in in_file_lines]))
out_file.close()
